FileNotFound: '{0} Source file is not found'
ColIndexNotFound : 'column {0} is out of range in datasource'
DataNotValid : 'datasource has some invalid data which are not correctly prepared for calculation'
ColumnNotFound: '{0} column  was not found'
ColumnsNotFound: 'one or more of mentiond columns  were not found: {0}'
ColIndexRangeNotFound: 'the range of columns is not valid: {0} - {1}'
CoeffPosStrong: 'the relation between data is strong positive'
CoeffPos: 'the relation between data is positive'
CoeffNegStrong: 'the relation between data is strong negative'
CoeffNeg: 'the relation between data is negative'