# source":"https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Country_codes

class countryCodes:

    twoLetterAbb = {
    "BE":"Belgium",
    "EL":"Greece",
    "LT":"Lithuania",
    "PT":"Portugal",
    "BG":"Bulgaria",
    "ES":"Spain",
    "LU":"Luxembourg",
    "RO":"Romania",
    "CZ":"Czechia",
    "FR":"France",
    "HU":"Hungary",
    "SI":"Slovenia",
    "DK":"Denmark",
    "HR":"Croatia",
    "MT":"Malta",
    "SK":"Slovakia",
    "DE":"Germany",
    "IT":"Italy",
    "NL":"Netherlands",
    "FI":"Finland",
    "EE":"Estonia",
    "CY":"Cyprus",
    "AT":"Austria",
    "SE":"Sweden",
    "IE":"Ireland",
    "LV":"Latvia",
    "PL":"Poland",
    "IS":"Iceland",
    "NO":"Norway",
    "CH":"Switzerland",
    "LI":"Liechtenstein",
    "UK":"United Kingdom",
    "BA":"Bosnia and Herzegovina",
    "ME":"Montenegro",
    "MD":"Moldova",
    "MK":"North Macedonia",
    "AL":"Albania",
    "RS":"Serbia",
    "Turkiye":"TR",
    "UA":"Ukraine",
    "XK":"Kosovo",
    "GE":"Georgia",
    "AM":"Armenia",
    "BY":"Belarus",
    "AZ":"Azerbaijan",
    "DZ":"Algeria",
    "LB":"Lebanon",
    "SY":"Syria",
    "EG":"Egypt",
    "LY":"Libya",
    "TN":"Tunisia",
    "IL":"Israel",
    "MA":"Morocco",
    "JO":"Jordan",
    "PS":"Palestine",
    "RU":"Russia",
    "AR":"Argentina",
    "CN_X_HK":"China",
    "MX":"Mexico",
    "ZA":"South Africa",
    "AU":"Australia",
    "HK":"Hong Kong",
    "NG":"Nigeria",
    "KR":"South Korea",
    "BR":"Brazil",
    "IN":"India",
    "NZ":"New Zealand",
    "TW":"Taiwan",
    "CA":"Canada",
    "JP":"Japan",
    "SG":"Singapore",
    "US":"United States"
    }